services:
  spark-master:
    build: ./master
    container_name: spark-master
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark master
    volumes:
      - ../data_lake:/data_lake
    env_file:
      - ../.env

  spark-worker:
    build: ./worker
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Spark worker UI
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ../.env

  jupyter:
    build:
      context: ../
      dockerfile: spark_docker/jupyter/Dockerfile
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      # - ../src:/home/jovyan/work
      # - ../data_lake:/data_lake
      # - ../data_source:/data_source
      # - ../utils:/alegra/utils
      # - ../puntos_scripts:/alegra/puntos_scripts
      # - ../docs:/alegra/docs
      # - ../.env:/home/jovyan/.env
      - ..:/alegra
    working_dir: /alegra
    depends_on:
      - spark-master
    env_file:
      - ../.env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/usr/local/spark
      - SPARK_URL=spark://spark-master:7077
      - PYTHONPATH=/alegra/src:/alegra/utils


  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_PID=${MSSQL_PID}
      - TZ=${TZ}
    volumes:
      - sql_data:/var/opt/mssql
      # - ./sql_server/init.sql:/init.sql
    
    # command: >
    #   bash -c "
    #     /opt/mssql/bin/sqlservr & 
    #     sleep 20 && 
    #     /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -i /init.sql
    #   "

volumes:
  sql_data:
